- hosts: localhost
  vars: 
    - admin_base_url: "http://192.168.99.100:8001"
    - api_base_url: "http://192.168.99.100:8000"
  
  tasks:
    
    - name: Add request transformer to mockbin 
      kong_plugin:
        kong_admin_uri: "{{admin_base_url}}"
        state: present
        api_name: "mockbin"
        plugin_name: "request-transformer"
        config: 
          "config.add.headers": "x-new-header:some_value, x-another-header:some_value"
          "config.add.querystring": "new-param:some_value, another-param:some_value"
          "config.add.form": "new-form-param:some_value, another-form-param:some_value"
          "config.remove.headers": "x-toremove, x-another-one"
          "config.remove.querystring": "param-toremove, param-another-one"
          "config.remove.form": "formparam-toremove, formparam-another-one"


    - debug: var=result   