cassandra:
  image: cassandra:2.2.4
  container_name: cassandra
  ports:
    - "9042:9042" 
web:
  image: mashape/kong
  container_name: kong
  ports:
    - "8000:8000"
    - "8443:8443"
    - "8001:8001"
    - "7946:7946"
    - "7946:7946/udp"
  links:
    - cassandra
ui:
  image: pgbi/kong-dashboard
  ports:
    - "8080:8080"
